# Generated by Django 6.0.3 on 2026-03-21 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='gusts_can_pause',
            new_name='guest_can_pause',
        ),
    ]
